# Generated by Django 4.2.2 on 2023-07-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_section', '0002_coursecategories_alter_courses_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='application',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='courses',
            name='duration',
            field=models.CharField(choices=[('1 Month', '1 Month'), ('2 Months', '2 Months'), ('3 Months', '3 Months'), ('6 Months', '6 Months'), ('9 Months', '9 Months')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='courses',
            name='fees',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
