# Generated by Django 4.2.2 on 2023-07-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_section', '0004_courses_created_at_courses_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
