# Generated by Django 4.2.2 on 2023-07-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_section', '0005_alter_courses_created_at_alter_courses_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='image',
            field=models.ImageField(default=None, upload_to='course_images'),
        ),
    ]
