# Generated by Django 4.2.2 on 2023-07-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_section', '0009_remove_courses_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='image',
            field=models.ImageField(default='D:/DATA SCIENCE/VS CODE/Django/learning_platform/python-logo.png', upload_to='course_images'),
        ),
    ]
