# Generated by Django 4.2.2 on 2023-07-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_section', '0010_courses_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.ImageField(default='/media/python-logo.png', upload_to='course_images'),
        ),
    ]
