# Generated by Django 4.2.2 on 2023-07-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_section', '0011_alter_courses_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.ImageField(default='', upload_to='course_section/images'),
        ),
    ]
